#!/bin/bash
# Copyright (C) 2018 by Tomas Herceg <tth@rfa.cz>
# Released under GNU GPL 3 or later

if [ -n "$SSH_ORIGINAL_COMMAND" ]; then
  if [[ "$SSH_ORIGINAL_COMMAND" =~ ^rsync\ --server\ --sender\  ]]; then
    echo "`/bin/date`: $SSH_CLIENT ALLOWED $SSH_ORIGINAL_COMMAND" >> $HOME/ssh-command-log
    exec $SSH_ORIGINAL_COMMAND
  else
    echo "`/bin/date`: $SSH_CLIENT DENIED $SSH_ORIGINAL_COMMAND" >> $HOME/ssh-command-log
  fi
fi
